apiVersion: v1
kind: Pod
metadata:
  name: nginx
  Namespace: roboshop
  labels: 
    names: nginx
    project: roboshop 
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
